app = "gopro-stream"

[env]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

[[services]]
  internal_port = 1935
  protocol = "tcp"

  [[services.ports]]
    port = 1935
